### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by 5T-23** [atmosphericbeats/atmosphericbeats_eveconfig_ksrss#1]
I'm having an issue with the volumetric clouds not appearing even after installing KSRSS and Blackracks Volumetric clouds. I just get a default flat layer of clouds any idea why this would be happening?
![image](https://user-images.githubusercontent.com/125355035/228171569-1da3850d-db93-4a09-8477-05e30f1f27bd.png)

I tried uninstalling everything and starting from scratch thinking maybe I messed something up along the way but I still have the same issue.

I also noticed that when opening EVE toolbar it says invalid name...

![image](https://user-images.githubusercontent.com/125355035/228170037-611d8824-0fd7-4a52-afd2-25b35115dd63.png)

but when going to mars your config seems to load fine the issue is only with earth.
![image](https://user-images.githubusercontent.com/125355035/228170162-a25e0312-2c25-44ef-8dd1-56863b34d816.png)

here is also a picture of my game data folder maybe I haven't installed something?
![image](https://user-images.githubusercontent.com/125355035/228170597-8c65c55d-9a7a-4e30-974e-bb9b414b0aac.png)

**Comment by 5T-23** [comment]
I figured it out.

I installed the master pack from gitlab instead of the reborn zip

**Comment by atmosphericbeats** [comment]
Nice, i'm gonna close the issue
