### ISSUE TITLE
Mars...

### ISSUE THREAD

**Issue by h3nt41c0m1c5** [atmosphericbeats/atmosphericbeats_eveconfig_ksrss#2]
Not sure if mars is supposed to look like this but it seems nothing like the example videos. 
![image](https://github.com/atmosphericbeats/atmosphericbeats_eveconfig_ksrss/assets/104699274/27790f7c-0956-45ab-87b0-0b3e2166ace2)

**Comment by atmosphericbeats** [comment]
Can you tell me if it's ok with the last release?
