### ISSUE TITLE
Any plan to update the cloud effect for Jupiter?

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [atmosphericbeats/atmosphericbeats_eveconfig_ksrss#4]
The new version of EVE has added a cloud vortex effect for Jool, do you plan to add it to Jupiter? Big thank to your work!

**Comment by atmosphericbeats** [comment]
Yeah, I'm already working on gas giants and on vortex effects on Earth too

**Comment by GIS-PuppetMaster** [comment]
> Yeah, I'm already working on gas giants and on vortex effects on Earth too

Thank you!
