### ISSUE TITLE
Unable to parse Venus-Fog1

### ISSUE THREAD

**Issue by sovetskysoyuz** [atmosphericbeats/atmosphericbeats_eveconfig_ksrss#5]
The Venus-Fog1 object is not parsed correctly because the coverageMap references StockVolumetricClouds/Clouds/Textures/DustScatteredCoverage. This texture does not exist. I believe StockVolumetricClouds/Clouds/Textures/Duna/DustScatteredCoverage is intended, as that is the only StockVolumetricClouds texture with that name.

Update: making that change does resolve the error in the log.

**Comment by JonnyOThan** [comment]
this is probably fixed with https://github.com/atmosphericbeats/atmosphericbeats_eveconfig_ksrss/pull/7

**Comment by atmosphericbeats** [comment]
Can you please try the new version for eve v3?
