### ISSUE TITLE
KSRSS-64k not working with EVE Volumetrics V3

### ISSUE THREAD

**Issue by AdrianDogmeat** [atmosphericbeats/atmosphericbeats_eveconfig_ksrss#8]

**Comment by atmosphericbeats** [comment]
Can you please try the new version? Regarding KSRSS-64k, use https://github.com/ballisticfox/KSP-64k. You don't need KSRSS-64k folder from Reborn repo anymore, you have to download Luna v1.1, Earth v1.1 and Mars v1.0 from KSP-64k project releases.
